[project]
name = "magic-list"
description = "Magic List is a module that extends the built-in list type."
version = "2.1.0"
keywords = ["collections", "list", "built-in", "extension"]

authors = [{ name = "Qexat", email = "contact@qexat.com" }]

requires-python = ">=3.9"

readme = "README.md"
license = { file = "LICENSE" }

classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Utilities",
    "Typing :: Typed",
]

[project.urls]
documentation = "https://qexat.github.io/magic-list/"
repository = "https://github.com/qexat/magic-list"

[project.optional-dependencies]
dev = [
    "build==1.2.*",
    "coverage==7.4.*",
    "pdoc==14.4.*",
    "pytest==7.4.*",
    "pyright==1.1.*",
    "twine==5.0.*",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
